@AudioWebApp.Server_HostAddress = https://localhost:8001

GET {{AudioWebApp.Server_HostAddress}}/api/announcements/getannouncements

###

GET {{AudioWebApp.Server_HostAddress}}/api/announcements/writeannouncements

###

GET {{AudioWebApp.Server_HostAddress}}/api/announcements/getlastupdateddate

###
